# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cinema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cinema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63inema.proto\x12\x06\x63inema\"3\n\tAssentoID\x12\x11\n\tsessao_id\x18\x01 \x01(\t\x12\x13\n\x0b\x61ssento_num\x18\x02 \x01(\t\"\x8c\x01\n\rStatusReserva\x12,\n\x06\x65stado\x18\x01 \x01(\x0e\x32\x1c.cinema.StatusReserva.Estado\x12\x10\n\x08mensagem\x18\x02 \x01(\t\";\n\x06\x45stado\x12\r\n\tRESERVADO\x10\x00\x12\x12\n\x0e\x42LOQUEADO_TEMP\x10\x01\x12\x0e\n\nDISPONIVEL\x10\x02\"H\n\x0eReservaRequest\x12\"\n\x07\x61ssento\x18\x01 \x01(\x0b\x32\x11.cinema.AssentoID\x12\x12\n\nusuario_id\x18\x02 \x01(\t\"K\n\x0fReservaResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x10\n\x08mensagem\x18\x02 \x01(\t\x12\x15\n\rreserva_token\x18\x03 \x01(\t2\x94\x01\n\x07Reserva\x12\x42\n\x0fReservarAssento\x12\x16.cinema.ReservaRequest\x1a\x17.cinema.ReservaResponse\x12\x45\n\x12\x43onfirmarPagamento\x12\x16.cinema.ReservaRequest\x1a\x17.cinema.ReservaResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cinema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASSENTOID']._serialized_start=24
  _globals['_ASSENTOID']._serialized_end=75
  _globals['_STATUSRESERVA']._serialized_start=78
  _globals['_STATUSRESERVA']._serialized_end=218
  _globals['_STATUSRESERVA_ESTADO']._serialized_start=159
  _globals['_STATUSRESERVA_ESTADO']._serialized_end=218
  _globals['_RESERVAREQUEST']._serialized_start=220
  _globals['_RESERVAREQUEST']._serialized_end=292
  _globals['_RESERVARESPONSE']._serialized_start=294
  _globals['_RESERVARESPONSE']._serialized_end=369
  _globals['_RESERVA']._serialized_start=372
  _globals['_RESERVA']._serialized_end=520
# @@protoc_insertion_point(module_scope)
