# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cinema_pb2 as cinema__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cinema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReservaStub(object):
    """Serviço RPC (Booking Service)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReservarAssento = channel.unary_unary(
                '/cinema.Reserva/ReservarAssento',
                request_serializer=cinema__pb2.ReservaRequest.SerializeToString,
                response_deserializer=cinema__pb2.ReservaResponse.FromString,
                _registered_method=True)
        self.ConfirmarPagamento = channel.unary_unary(
                '/cinema.Reserva/ConfirmarPagamento',
                request_serializer=cinema__pb2.ReservaRequest.SerializeToString,
                response_deserializer=cinema__pb2.ReservaResponse.FromString,
                _registered_method=True)


class ReservaServicer(object):
    """Serviço RPC (Booking Service)
    """

    def ReservarAssento(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfirmarPagamento(self, request, context):
        """Simulação de confirmação
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReservaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReservarAssento': grpc.unary_unary_rpc_method_handler(
                    servicer.ReservarAssento,
                    request_deserializer=cinema__pb2.ReservaRequest.FromString,
                    response_serializer=cinema__pb2.ReservaResponse.SerializeToString,
            ),
            'ConfirmarPagamento': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfirmarPagamento,
                    request_deserializer=cinema__pb2.ReservaRequest.FromString,
                    response_serializer=cinema__pb2.ReservaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cinema.Reserva', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cinema.Reserva', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Reserva(object):
    """Serviço RPC (Booking Service)
    """

    @staticmethod
    def ReservarAssento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cinema.Reserva/ReservarAssento',
            cinema__pb2.ReservaRequest.SerializeToString,
            cinema__pb2.ReservaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfirmarPagamento(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cinema.Reserva/ConfirmarPagamento',
            cinema__pb2.ReservaRequest.SerializeToString,
            cinema__pb2.ReservaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
